#!/bin/bash

RESET=`tput sgr0`
RED=`tput setaf 1`
GREEN=`tput setaf 2`
YELLOW=`tput setaf 3`
BLUE=`tput setaf 4`
PURPLE=`tput setaf 5`
LBLUE=`tput setaf 6`


case $1 in

  red)
    echo -n "${RED}$2${RESET}"
    ;;
  green)
    echo -n "${GREEN}$2${RESET}"
    ;;
  yellow)
    echo -n "${YELLOW}$2${RESET}"
    ;;
  blue)
    echo -n "${BLUE}$2${RESET}"
    ;;
  purple)
    echo -n "${PURPLE}$2${RESET}"
    ;;
  lblue)
    echo -n "${LBLUE}$2${RESET}"
    ;;

  *)
    echo -n "$2"
    ;;
  esac
